version: '3'
services:
  mysql-server:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql-server
    restart: always
  Department-Rest:
    image: vihangat/rest-department-api:latest
    ports:
      - 9080:9080
    environment:
      - Deployment-Rest-Backend/configs/application.properties
    container_name: Deployment-Rest-Backend
    restart: always
volumes:
  mysql-data:
    driver: local