server:
  port: 9999
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/rest
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
    show-sql: true
test:
  message: '"Hellow World"'