server:
  port: 9999
spring:
  profiles:
    active: dev
#logging:
#  level: root
#  config: logback.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"



---
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/rest
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
    show-sql: true
  config:
    activate:
      on-profile: dev
test:
  message: "Hellow World"

---
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/restProduction
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
    show-sql: true
  config:
    activate:
      on-profile: Production
test:
  message: "Hellow World"

---
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/restQA
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
    show-sql: true
  config:
    activate:
      on-profile: QA
test:
  message: "Hellow World"